### ISSUE TITLE
maxVolume reporting as 0 with traffic

### ISSUE THREAD

**Issue by garadox** [OskarKjellin/vizceral-hystrix#1]
I'm not sure if this is an issue with turbine, but with 1.0.3 of vizceral-hystrix the maxVolume per cluster and overall is reporting 0 all the time.

I dug into the turbine stream and it appears that rollingCountEmit is 0 even when rollingCountSuccess is > 0. 

I don't know enough about turbine to know if this is a valid case - should this app be using rollingCountSuccess for the total?

**Comment by OskarKjellin** [comment]
Sorry for the late reply. 
What versions of hystrix, hystrix-stream and turbine are you running? Sounds like an issue in those, or a version mismatch

**Comment by garadox** [comment]
Turbine: 1.0.0
Hystrix: 1.5.1
I'm guessing turbine is the one using Hystrix-Stream, but i'm not sure what version it is.

**Comment by garadox** [comment]
I agree that it's probably a version mismatch, but not sure who's at fault...

**Comment by OskarKjellin** [comment]
We're running turbine 1.0.0. so I guess that's not at fault.
Of hystrix we're running 1.5.5, so doesn't sound like that would be an issue either.

Regarding the "hystrix stream" I was referring to, it's this one: http://mvnrepository.com/artifact/com.netflix.hystrix/hystrix-metrics-event-stream

It's something that you put into your app in order to get the servlet exposing the stream. Should generally be on the same version as hystrix

**Comment by garadox** [comment]
Found it. We're using the same version of Hystrix and hystrix-metrics-event-stream - 1.5.1.

**Comment by OskarKjellin** [comment]
My guess is that it's a bug in Hystrix actually. I managed to reproduce. It happens if you use thread isolation strategy. Do you do that?
We always use semapore, which is why we weren't hit by it.
I'll create a patch which pretty much takes the max of 
`Math.max(rollingCountEmit, rollingCountBadRequests+rollingCountCollapsedRequests + rollingCountExceptionsThrown + rollingCountFailure + rollingCountFallbackFailure + rollingCountFallbackMissing + rollingCountFallbackRejection + rollingCountFallbackSuccess + rollingCountResponsesFromCache + rollingCountSemaphoreRejected + rollingCountShortCircuited + rollingCountSuccess + rollingCountThreadPoolRejected +rollingCountTimeout)`

**Comment by garadox** [comment]
The default `execution.isolation.strategy` is THREAD, and I don't believe we've changed the default setting.

The patch would be a nice workaround :)

**Comment by OskarKjellin** [comment]
Well if you use rx (observables) the default is SEMAPHORES. I just reread the documentation and noticed that the EMIT values are only valid for HystrixObservableCommand. So my bad

**Comment by OskarKjellin** [comment]
@garadox should be OK now :) I used the requestCount field. 
Thanks for reporting! 
Let me know if this resolved your issue.

**Comment by garadox** [comment]
Will requestCount work the same way as rolling counts, or is it just a cumulative total that will only increase over time?

**Comment by OskarKjellin** [comment]
It works the same as the other. At least when I had a look at our production data it matched rollingCountSuccess 100%

**Comment by garadox** [comment]
I'll try it out and let you know the results. Thanks!

**Comment by garadox** [comment]
Confirmed i'm getting maxVolume populated in 1.0.4 with requestCount. Thanks!
